import numpy
import pandas
import sklearn
import xgboost
import catboost
import matplotlib
import seaborn
import plotly
import nbformat
import streamlit

print("NumPy:", numpy.__version__)
print("Pandas:", pandas.__version__)
print("Scikit-learn:", sklearn.__version__)
print("XGBoost:", xgboost.__version__)
print("CatBoost:", catboost.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Seaborn:", seaborn.__version__)
print("Plotly:", plotly.__version__)
print("nbformat:", nbformat.__version__)
print("Streamlit:", streamlit.__version__)
